
package ru.geekbrains.enterprise.testsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestSOAPServiceService", targetNamespace = "http://test.service.enterprise.geekbrains.ru/", wsdlLocation = "http://localhost:8080/TestSOAPService?wsdl")
public class TestSOAPServiceService
    extends Service
{

    private final static URL TESTSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSOAPSERVICESERVICE_EXCEPTION;
    private final static QName TESTSOAPSERVICESERVICE_QNAME = new QName("http://test.service.enterprise.geekbrains.ru/", "TestSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TestSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSOAPSERVICESERVICE_WSDL_LOCATION = url;
        TESTSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public TestSOAPServiceService() {
        super(__getWsdlLocation(), TESTSOAPSERVICESERVICE_QNAME);
    }

    public TestSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSOAPSERVICESERVICE_QNAME, features);
    }

    public TestSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTSOAPSERVICESERVICE_QNAME);
    }

    public TestSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSOAPSERVICESERVICE_QNAME, features);
    }

    public TestSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestSOAPService
     */
    @WebEndpoint(name = "TestSOAPServicePort")
    public TestSOAPService getTestSOAPServicePort() {
        return super.getPort(new QName("http://test.service.enterprise.geekbrains.ru/", "TestSOAPServicePort"), TestSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestSOAPService
     */
    @WebEndpoint(name = "TestSOAPServicePort")
    public TestSOAPService getTestSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.service.enterprise.geekbrains.ru/", "TestSOAPServicePort"), TestSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw TESTSOAPSERVICESERVICE_EXCEPTION;
        }
        return TESTSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
